import { expect, test } from '@playwright/test';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// Browser smoke for every pyodide test contract (ADR-0013 inherited-debt A).
// Mirrors gradePython() exactly: same tests, packages, seed, timeout budget.
// For every definition it runs the reference solver (must pass all tests) and
// a broken solution (must be rejected). Timeout and worker restart are checked
// once per session at contract level. The run writes a machine-readable
// receipt that tests/pyodide_contract_matrix.test.mjs enforces, so no pyodide
// family can claim browser verification without this spec having run.

// Generated by tools/pyodide_contract_matrix.mjs; freshness is enforced by
// tests/pyodide_contract_matrix.test.mjs. Playwright loads specs as CJS here,
// so the ESM tool cannot be imported directly.
const matrixPath = join(process.cwd(), 'tests/e2e/pyodide-contract-matrix.json');
const matrix = JSON.parse(readFileSync(matrixPath, 'utf8')) as {
  definitions: Array<{ definitionId: string; weekId: string; packages: string[]; tests: string; referenceSolver: string; contract: string; verificationHash: string }>;
};

interface ContractDefinition {
  definitionId: string;
  weekId: string;
  packages: string[];
  tests: string;
  referenceSolver: string;
  contract: string;
  verificationHash: string;
}

interface RunRecord {
  definitionId: string;
  referencePassed: boolean;
  brokenRejected: boolean;
  referenceRun: { tests: number; [key: string]: unknown };
  [key: string]: unknown;
}

interface WorkerProbe {
  timeoutProbe: { phase: string };
  restartProbe: { ok: boolean; stdout: string };
}

test('every pyodide exercise contract passes and rejects in the browser worker', async ({ page, browserName }) => {
  test.skip(browserName !== 'chromium', 'Der Pyodide-Vertragssmoke läuft in Chromium.');
  test.setTimeout(600000);
  await page.goto('/index.html#/today');
  await expect(page.getByRole('heading', { level: 1, name: 'Heute' })).toBeVisible();

  const results = await page.evaluate(async (definitions: ContractDefinition[]) => {
    const runnerUrl = '/assets/js/runtime/pyodide_runner.js';
    const { pyodideRunner, PyodideRunner } = (await import(runnerUrl)) as { pyodideRunner: {
      run: (payload: { code: string; tests: string; packages: string[]; seed: number; timeoutMs: number }) => Promise<{
        ok: boolean;
        phase: string;
        errorType: string | null;
        stdout: string;
        durationMs: number;
        testResults?: Array<{ passed: boolean }>;
      }>;
    }; PyodideRunner: new (url: string) => {
      run: (payload: { code: string; tests: string; packages: string[]; seed: number; timeoutMs: number }) => Promise<{
        ok: boolean;
        phase: string;
        errorType: string | null;
        stdout: string;
        durationMs: number;
        testResults?: Array<{ passed: boolean }>;
      }>;
    } };
    type Runner = typeof pyodideRunner;
    // Zwei Worker parallel: der Runner pipelined pro Worker, jeder Worker
    // rechnet sequentiell — die 188 Runs halbieren sich so auf der Wanduhr.
    const secondRunner = new PyodideRunner('assets/js/runtime/pyodide_worker.mjs');
    const runResults: RunRecord[] = new Array(definitions.length);
    const runSlice = async (runner: Runner, defs: Array<{ index: number; definition: ContractDefinition }>) => {
      for (const { index, definition } of defs) {
        const reference = await runner.run({
          code: definition.referenceSolver,
          tests: definition.tests,
          packages: definition.packages,
          seed: 42,
          timeoutMs: 60000,
        });
        const referenceTestResults = reference.testResults || [];
        const referencePassed = reference.ok
          && referenceTestResults.length > 0
          && referenceTestResults.every((item) => item.passed);
        const broken = await runner.run({
          code: 'pass',
          tests: definition.tests,
          packages: definition.packages,
          seed: 42,
          timeoutMs: 60000,
        });
        const brokenRejected = !broken.ok || !(broken.testResults || []).every((item: { passed: boolean }) => item.passed);
        runResults[index] = {
          definitionId: definition.definitionId,
          weekId: definition.weekId,
          contract: definition.contract,
          verificationHash: definition.verificationHash,
          referenceRun: { ok: reference.ok, tests: referenceTestResults.length, errorType: reference.errorType, phase: reference.phase, durationMs: reference.durationMs },
          referencePassed,
          brokenRejected,
          brokenRun: { ok: broken.ok, errorType: broken.errorType, phase: broken.phase, durationMs: broken.durationMs },
        };
      }
    };
    const indexed = definitions.map((definition, index) => ({ index, definition }));
    await Promise.all([
      runSlice(pyodideRunner, indexed.filter((item) => item.index % 2 === 0)),
      runSlice(secondRunner, indexed.filter((item) => item.index % 2 === 1)),
    ]);
    const timeoutProbe = await pyodideRunner.run({
      code: 'while True:\n    pass',
      tests: '',
      packages: [],
      seed: 1,
      timeoutMs: 1500,
    });
    const afterRestart = await pyodideRunner.run({
      code: 'print("restarted")',
      tests: '',
      packages: [],
      seed: 2,
      timeoutMs: 30000,
    });
    return {
      runResults,
      timeoutProbe: { phase: timeoutProbe.phase, errorType: timeoutProbe.errorType },
      restartProbe: { ok: afterRestart.ok, stdout: afterRestart.stdout },
    };
  }, matrix.definitions);

  const failures = (results as { runResults: RunRecord[] }).runResults.filter((item) => !item.referencePassed || !item.brokenRejected);
  for (const item of failures) {
    console.error(`PYODIDE CONTRACT FAILURE: ${item.definitionId} referencePassed=${item.referencePassed} brokenRejected=${item.brokenRejected} run=${JSON.stringify(item)}`);
  }
  expect(failures, `pyodide definitions failing their browser contract: ${failures.map((item) => item.definitionId).join(', ')}`).toEqual([]);
  const probe = results as unknown as WorkerProbe;
  expect(probe.timeoutProbe.phase).toBe('timeout');
  expect(probe.restartProbe.ok).toBe(true);
  expect(probe.restartProbe.stdout.trim()).toBe('restarted');

  const receipt = {
    schemaVersion: 1,
    browser: 'chromium',
    artifact: process.env.PLAYWRIGHT_PREVIEW === '1' ? 'build' : 'dev',
    ranAt: new Date().toISOString(),
    definitionCount: results.runResults.length,
    contractCount: new Set(results.runResults.map((item) => item.contract)).size,
    timeoutProbe: results.timeoutProbe,
    restartProbe: results.restartProbe,
    results: (results as { runResults: unknown[] }).runResults,
  };
  const receiptDir = join(process.cwd(), 'tests/e2e');
  mkdirSync(receiptDir, { recursive: true });
  writeFileSync(join(receiptDir, 'pyodide-contract-receipt.json'), JSON.stringify(receipt, null, 2) + '\n');
});
